// <auto-generated />
using System;
using LegalCaseManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace lpms_server.Migrations
{
    [DbContext(typeof(LegalCaseDbContext))]
    [Migration("20251020141438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LegalCaseManagement.Models.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseId"));

                    b.Property<int>("AssignedLawyerId")
                        .HasColumnType("int");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateFiled")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Outcome")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CaseId");

                    b.HasIndex("AssignedLawyerId");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("CourtId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("LegalCaseManagement.Models.CaseParty", b =>
                {
                    b.Property<int>("CasePartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CasePartyId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CasePartyId");

                    b.HasIndex("PartyId");

                    b.HasIndex("CaseId", "PartyId", "Role")
                        .IsUnique();

                    b.ToTable("CaseParties");
                });

            modelBuilder.Entity("LegalCaseManagement.Models.Court", b =>
                {
                    b.Property<int>("CourtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourtId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CourtId");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            CourtId = 1,
                            Address = "123 Justice Blvd",
                            City = "Downtown",
                            CreatedAt = new DateTime(2025, 10, 20, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Superior Court of Justice",
                            Phone = "555-0201",
                            State = "CA",
                            Type = "Superior",
                            ZipCode = "90210"
                        },
                        new
                        {
                            CourtId = 2,
                            Address = "456 Court Street",
                            City = "Midtown",
                            CreatedAt = new DateTime(2025, 10, 20, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "District Court",
                            Phone = "555-0202",
                            State = "CA",
                            Type = "District",
                            ZipCode = "90211"
                        });
                });

            modelBuilder.Entity("LegalCaseManagement.Models.Deadline", b =>
                {
                    b.Property<int>("DeadlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeadlineId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Medium");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DeadlineId");

                    b.HasIndex("CaseId");

                    b.ToTable("Deadlines");
                });

            modelBuilder.Entity("LegalCaseManagement.Models.Hearing", b =>
                {
                    b.Property<int>("HearingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HearingId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int?>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("HearingType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Scheduled");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("HearingId");

                    b.HasIndex("CaseId");

                    b.HasIndex("CourtId");

                    b.ToTable("Hearings");
                });

            modelBuilder.Entity("LegalCaseManagement.Models.Lawyer", b =>
                {
                    b.Property<int>("LawyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LawyerId"));

                    b.Property<string>("BarNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LawyerId");

                    b.HasIndex("BarNumber")
                        .IsUnique()
                        .HasFilter("[BarNumber] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Lawyers");

                    b.HasData(
                        new
                        {
                            LawyerId = 1,
                            BarNumber = "BAR001",
                            CreatedAt = new DateTime(2025, 10, 20, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.smith@lawfirm.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Smith",
                            Phone = "555-0101",
                            Specialization = "Criminal Law"
                        },
                        new
                        {
                            LawyerId = 2,
                            BarNumber = "BAR002",
                            CreatedAt = new DateTime(2025, 10, 20, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.johnson@lawfirm.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Johnson",
                            Phone = "555-0102",
                            Specialization = "Civil Law"
                        });
                });

            modelBuilder.Entity("LegalCaseManagement.Models.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartyId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartyType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PartyId");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            PartyId = 1,
                            Address = "789 Main Street",
                            City = "Downtown",
                            CreatedAt = new DateTime(2025, 10, 20, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.williams@email.com",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Williams",
                            PartyType = "Individual",
                            Phone = "555-0301",
                            State = "CA",
                            ZipCode = "90210"
                        },
                        new
                        {
                            PartyId = 2,
                            Address = "321 Oak Avenue",
                            City = "Uptown",
                            CreatedAt = new DateTime(2025, 10, 20, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.davis@email.com",
                            FirstName = "Bob",
                            IsActive = true,
                            LastName = "Davis",
                            PartyType = "Individual",
                            Phone = "555-0302",
                            State = "CA",
                            ZipCode = "90212"
                        });
                });

            modelBuilder.Entity("LegalCaseManagement.Models.Case", b =>
                {
                    b.HasOne("LegalCaseManagement.Models.Lawyer", "AssignedLawyer")
                        .WithMany("Cases")
                        .HasForeignKey("AssignedLawyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalCaseManagement.Models.Court", "Court")
                        .WithMany("Cases")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedLawyer");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("LegalCaseManagement.Models.CaseParty", b =>
                {
                    b.HasOne("LegalCaseManagement.Models.Case", "Case")
                        .WithMany("CaseParties")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalCaseManagement.Models.Party", "Party")
                        .WithMany("CaseParties")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("LegalCaseManagement.Models.Deadline", b =>
                {
                    b.HasOne("LegalCaseManagement.Models.Case", "Case")
                        .WithMany("Deadlines")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("LegalCaseManagement.Models.Hearing", b =>
                {
                    b.HasOne("LegalCaseManagement.Models.Case", "Case")
                        .WithMany("Hearings")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalCaseManagement.Models.Court", "Court")
                        .WithMany("Hearings")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Case");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("LegalCaseManagement.Models.Case", b =>
                {
                    b.Navigation("CaseParties");

                    b.Navigation("Deadlines");

                    b.Navigation("Hearings");
                });

            modelBuilder.Entity("LegalCaseManagement.Models.Court", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Hearings");
                });

            modelBuilder.Entity("LegalCaseManagement.Models.Lawyer", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("LegalCaseManagement.Models.Party", b =>
                {
                    b.Navigation("CaseParties");
                });
#pragma warning restore 612, 618
        }
    }
}
